# To make basic sanity check

name: code-sanity 
run-name: ${{ github.actor }} is running code santiy check 🚀
on:
    push:
        branches:
            - task/*
jobs:
    lint-job:
        runs-on: solinas-small
        steps:
            - name: installing dependencies
              run: npm install
            - name: running lint
              run: npm run lint

    test-job:
      runs-on: solinas-small
      steps:
          - name: installing dependencies
            run: npm install
          - name: running tests
            run: npm run test


